name: green_apple_pay
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  line_icons: ^2.0.1
  intl: ^0.17.0
  flutter_slidable: ^0.6.0
  provider: ^5.0.0
  fluttertoast: ^8.0.7
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  flutter_vector_icons: ^1.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Black.ttf
        - asset: fonts/inter/Inter-BlackItalic.ttf
        - asset: fonts/inter/Inter-Bold.ttf
        - asset: fonts/inter/Inter-BoldItalic.ttf
        - asset: fonts/inter/Inter-ExtraBold.ttf
        - asset: fonts/inter/Inter-ExtraBoldItalic.ttf
        - asset: fonts/inter/Inter-ExtraLight.ttf
        - asset: fonts/inter/Inter-ExtraLightItalic.ttf
        - asset: fonts/inter/Inter-Italic.ttf
        - asset: fonts/inter/Inter-Light.ttf
        - asset: fonts/inter/Inter-LightItalic.ttf
        - asset: fonts/inter/Inter-Medium.ttf
        - asset: fonts/inter/Inter-MediumItalic.ttf
        - asset: fonts/inter/Inter-Regular.ttf
        - asset: fonts/inter/Inter-SemiBold.ttf
        - asset: fonts/inter/Inter-SemiBoldItalic.ttf
        - asset: fonts/inter/Inter-Thin.ttf
        - asset: fonts/inter/Inter-ThinItalic.ttf